- name: create registry user
  user:
    name: registry
    create_home: no
    groups:
      - docker
    state: present

- name: pull the docker image
  docker_image:
    name: "registry:{{ registry_version }}"
    source: pull
    force_source: yes
  retries: 8
  ignore_errors: yes

- name: create folders
  file:
    path: "/opt/registry"
    owner: registry
    group: registry
    mode: "0755"
    state: directory

- name: create systemd
  template:
    src: service.j2
    dest: "/etc/systemd/system/registry.service"
    owner: root
    group: root
    mode: "0644"
  notify: restart container 
