- name: load vars
  include_vars:
    file: "vars/{{ cluster }}.yml"
  failed_when: false

- name: install packages
  import_tasks: install.yml
- name: create new user and pull docker
  import_tasks: configure.yml

- name: ensure registry has started
  systemd:
    name: registry
    daemon-reload: yes
    enabled: yes
    state: started
